# Generated by Django 4.2 on 2023-05-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='image',
            field=models.ImageField(default='images/centers/default-placeholder.png', upload_to='images/centers/profile_images/'),
        ),
    ]
