# Generated by Django 4.2 on 2023-05-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_center_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='excerpt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
