# Generated by Django 4.2 on 2023-06-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_image_specialist_personal_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialist',
            old_name='personal_image',
            new_name='image',
        ),
    ]
