# Generated by Django 4.2 on 2023-05-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_center_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
