# Generated by Django 4.2.2 on 2023-06-19 01:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_personal_image_specialist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=9),
        ),
    ]
