# Generated by Django 4.2.2 on 2023-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_specialist_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
