# Generated by Django 4.2 on 2023-05-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_center_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
    ]
