# Generated by Django 4.2 on 2023-05-24 15:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_specialist_excerpt_specialist_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('our_profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('duration_in_days', models.IntegerField()),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.specialist')),
            ],
            options={
                'unique_together': {('specialist', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='SpecialistReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialist_reviews', to='users.client')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.specialist')),
            ],
            options={
                'unique_together': {('client', 'specialist')},
            },
        ),
    ]
