# Generated by Django 4.2 on 2023-06-17 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('specialists', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistCertifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/specialists/certifications/')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='users.specialist')),
            ],
        ),
    ]
