# Generated by Django 4.2.2 on 2023-06-19 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_specialist_service_price'),
        ('specialists', '0004_rename_image_specialistcertifications_certification_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialistTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('our_profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.specialist')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('duration_in_days', models.IntegerField()),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.specialist')),
            ],
            options={
                'unique_together': {('specialist', 'start_date')},
            },
        ),
    ]
