# Generated by Django 4.2.2 on 2023-06-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialists', '0005_specialisttransactions_clientsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialisttransactions',
            name='specialist',
        ),
        migrations.DeleteModel(
            name='ClientSubscription',
        ),
        migrations.DeleteModel(
            name='SpecialistTransactions',
        ),
    ]
