# Generated by Django 4.2 on 2023-05-23 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_center_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.center')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_reviews', to='users.client')),
            ],
            options={
                'unique_together': {('client', 'center')},
            },
        ),
    ]
