# Generated by Django 4.2 on 2023-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centerreviews',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
