# Generated by Django 4.2 on 2023-06-07 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centertransactions',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.center'),
        ),
        migrations.AddField(
            model_name='centersubscription',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.center'),
        ),
        migrations.AddField(
            model_name='centerreviews',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.center'),
        ),
        migrations.AddField(
            model_name='centerreviews',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_reviews', to='users.client'),
        ),
        migrations.AlterUniqueTogether(
            name='centersubscription',
            unique_together={('center', 'start_date')},
        ),
        migrations.AlterUniqueTogether(
            name='centerreviews',
            unique_together={('client', 'center')},
        ),
    ]
