# Generated by Django 4.2 on 2023-05-23 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_center_is_subscribed'),
        ('centers', '0002_alter_centerreviews_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('our_profit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.center')),
            ],
        ),
        migrations.CreateModel(
            name='CenterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('duration_in_days', models.IntegerField()),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.center')),
            ],
            options={
                'unique_together': {('center', 'start_date')},
            },
        ),
    ]
